#!/bin/sh -e
path="."
if [ x"$1" != x ]; then
	path="$1"
fi

versionsvn() {
	touch $path/comptime.c
	svnrevision=`svnversion -n $1`
    cat <<EOF > $path/comptime.h

// Do not edit!  This file was autogenerated
// by the $0 script
//
const char* comprevision = "$svnrevision";
EOF
}

compversion() {
test -d $path/.svn && versionsvn
}

test -f $path/comptime.c && compversion
