#
# win32/Makefile.cfg for SRB2/Minwgw
#

#
#Mingw, if you don't know, that's Win32/Win64
#

D_FILES+=$(D_DIR)/fmod.dll

ifdef MINGW64
	NOASM=1
	NONX86=1
endif

ifndef NOASM
	USEASM=1
endif

	OPTS=-DSTDC_HEADERS

ifndef GCC44
	#OPTS+=-mms-bitfields
endif

ifndef SDL
	OPTS+=-D_WINDOWS
endif
ifdef NOFMOD
	OPTS+=-DNOFMOD
endif
	OPTS+=-D__USE_MINGW_ANSI_STDIO=0

ifndef SDL
	LIBS+=-lmingw32 -mwindows -ldinput -ldxguid -lgdi32 -lwinmm
endif

	LIBS+=-ladvapi32 -lkernel32 -lmsvcrt -luser32
ifdef MINGW64
	LIBS+=-lws2_32
else
	LIBS+=-lwsock32
endif

	# name of the exefile
ifdef SDL
	EXENAME?=srb2sdl.exe
else
	EXENAME?=srb2win.exe
endif

ifdef SDL
	i_system_o+=$(OBJDIR)/SRB2.res
	i_main_o+=$(OBJDIR)/win_dbg.o
ifndef NOHW
	OPTS+=-DUSE_WGL_SWAP
endif
else
	i_cdmus_o=$(OBJDIR)/win_cd.o
	i_net_o=$(OBJDIR)/win_net.o
	i_system_o=$(OBJDIR)/win_sys.o $(OBJDIR)/SRB2.res
	i_sound_o=$(OBJDIR)/win_snd.o $(OBJDIR)/mid2strm.o
	i_main_o=$(OBJDIR)/win_dbg.o $(OBJDIR)/win_main.o
	OBJS=$(OBJDIR)/dx_error.o $(OBJDIR)/fabdxlib.o $(OBJDIR)/win_vid.o $(OBJDIR)/win_dll.o
endif

ifndef NOPNG
ifndef PNG_CONFIG
	PNG_CFLAGS?=-I../libs/libpng-src -I../libs/zlib
ifdef MINGW64
	PNG_LDFLAGS?=-L../libs/libpng-src/projects -lpng64 -L../libs/zlib/win32 -lz64
else
	PNG_LDFLAGS?=-L../libs/libpng-src/projects -lpng32 -L../libs/zlib/win32 -lz32
endif #MINGW64
endif #PNG_CONFIG
endif #NOPNG

ifdef GETTEXT
ifndef CCBS
	MSGFMT?=../tools/gettext/bin32/msgfmt.exe
endif
ifdef MINGW64
	CPPFLAGS+=-I../tools/gettext/include64
	LDFLAGS+=-L../tools/gettext/lib64
	LIBS+=-lmingwex
else
	CPPFLAGS+=-I../tools/gettext/include32
	LDFLAGS+=-L../tools/gettext/lib32
	STATIC_GETTEXT=1
endif #MINGW64
ifdef STATIC_GETTEXT
	LIBS+=-lasprintf -lintl
else
	LIBS+=-lintl.dll
endif #STATIC_GETTEXT
endif #GETTEXT

